version: "3.4"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    volumes:
      - /Users/brian/Desktop/dev-.NetCore/DB-Volume:/var/opt/mssql/data
      
    environment:
      SA_PASSWORD: "8ri@N9538!"
      ACCEPT_EULA: "Y"